import { useNavigate } from 'react-router-dom';

export default function LandingPage() {
    const navigate = useNavigate();

    return (
        <div className="container">
            <header className="header">
                <div className="logo">
                    <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect width="40" height="40" rx="8" fill="url(#logo-gradient)" />
                        <path d="M20 10L25 15H22.5V22.5H25L20 27.5L15 22.5H17.5V15H15L20 10Z" fill="white" />
                        <defs>
                            <linearGradient id="logo-gradient" x1="0" y1="0" x2="40" y2="40">
                                <stop offset="0%" stopColor="#667eea" />
                                <stop offset="100%" stopColor="#764ba2" />
                            </linearGradient>
                        </defs>
                    </svg>
                    <span className="logo-text">Interview Saathi</span>
                </div>
                <nav className="nav">
                    <a href="#features" className="nav-link">Features</a>
                    <a href="#how-it-works" className="nav-link">How It Works</a>
                </nav>
            </header>

            <div className="hero">
                <div className="hero-badge">
                    <span className="badge-dot"></span>
                    <span>AI-Powered Interview Practice</span>
                </div>
                <h1 className="hero-title">
                    Ace Your Next Interview with
                    <span className="gradient-text"> AI-Powered Practice</span>
                </h1>
                <p className="hero-description">
                    Practice realistic mock interviews tailored to your role, tech stack, and experience level.
                    Get instant AI-driven feedback to improve your performance and build confidence.
                </p>
                <div className="hero-cta">
                    <button onClick={() => navigate('/setup')} className="btn btn-primary">
                        <span>Start Mock Interview</span>
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4 10H16M16 10L11 5M16 10L11 15" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                    </button>
                    <button className="btn btn-secondary" onClick={() => document.getElementById('how-it-works').scrollIntoView({ behavior: 'smooth' })}>
                        Learn More
                    </button>
                </div>

                <div className="hero-stats">
                    <div className="stat">
                        <div className="stat-value">500+</div>
                        <div className="stat-label">Questions</div>
                    </div>
                    <div className="stat">
                        <div className="stat-value">10+</div>
                        <div className="stat-label">Tech Stacks</div>
                    </div>
                    <div className="stat">
                        <div className="stat-value">100%</div>
                        <div className="stat-label">AI-Powered</div>
                    </div>
                </div>
            </div>

            <div id="features" className="features">
                <h2 className="section-title">Why Choose Interview Saathi?</h2>
                <div className="features-grid">
                    <div className="feature-card">
                        <div className="feature-icon">🎯</div>
                        <h3>Personalized Practice</h3>
                        <p>Customize interviews based on your target role, technology stack, and experience level</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">🤖</div>
                        <h3>AI-Driven Questions</h3>
                        <p>Get realistic questions generated by AI that match real interview scenarios</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">🎤</div>
                        <h3>Voice Interaction</h3>
                        <p>Practice with voice input and output for a truly immersive interview experience</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">📊</div>
                        <h3>Detailed Feedback</h3>
                        <p>Receive comprehensive analysis with scores, strengths, and areas for improvement</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">⚡</div>
                        <h3>Instant Results</h3>
                        <p>Get immediate feedback after each interview session to track your progress</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">🔒</div>
                        <h3>Private & Secure</h3>
                        <p>Your interview sessions are private and stored locally on your device</p>
                    </div>
                </div>
            </div>

            <div id="how-it-works" className="how-it-works">
                <h2 className="section-title">How It Works</h2>
                <div className="steps">
                    <div className="step">
                        <div className="step-number">1</div>
                        <div className="step-content">
                            <h3>Choose Your Parameters</h3>
                            <p>Select your target role, technology stack, experience level, and interview round type</p>
                        </div>
                    </div>
                    <div className="step">
                        <div className="step-number">2</div>
                        <div className="step-content">
                            <h3>Conduct Mock Interview</h3>
                            <p>Answer AI-generated questions using voice or text in a realistic interview environment</p>
                        </div>
                    </div>
                    <div className="step">
                        <div className="step-number">3</div>
                        <div className="step-content">
                            <h3>Receive Detailed Feedback</h3>
                            <p>Get comprehensive analysis with scores, answer reviews, and personalized improvement tips</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
